# UTS-2 My Songs for You

Miracle Paint
Artist: OSTER project

{{< video https://youtu.be/gqPWXe0dCC4?si=k40nbA5UKidbONYL>}}, with lyrics

しゃーばーだばっぱっぱっぱらっぱ
しゃーばだばったーとぅりらっぱら
しゃーばーだばっぱっぱっぱらっぱ
しゃーばーだばっぱ
しゃばでぃらーとぅりらーぱりらーとぅりら
しゃばでぃらーとぅりるりーだだーてぃらる
しゃばでぃらーとぅりらーぱりらーぱっりーらー
（しゃーばーだばっぱっぱっぱ）

夕闇のキャンバスに ワインレッドの夕日を
見送った 帰り道
あなたのハートは もう私のこと描いてるのかな

今夜は 時間もたっぷりあるから
あなただけの 私でいてあげるよ
ゆっくりと深呼吸して 見つめ合ったら
始まるよ

Miracle painting
キセキのshow time
魔法の一筆で 夢中にさせて
爪の先まで全て あなた色に染めて
とぅりらぷーりらっぱっぱー
りらる るぷりら らぱるぱ
らるり るぱりらる らぱるぴら
とぅら とぅりら るぱるぱるぱるぱ
ぴらるーら しゃばだでぃーら
ぱーるら ぱりりら るらるらるらるら
しゃーばだっ とぅらるしゃばでぃらー
とぅらばだでぃらでぃらでぃらだ
ぱりらりらるぴらば
ぴる ぴるとぅらとぅりらっとぅらる

ぱるりりぱらぱ しゃばどぅりららる
りら るらるりらーぱっぱっぴーら るらーら
るらるらりらーあー

ぴらる しゃーばーだばっぱっぱっぱらっぱ
あーぁ（しゃーばーだばっぱっぱっぱ）

お気に入りのドレスに
星空のライムライト浴びながら
得意げに 踊るつま先を
必死に見つめるあなた 嬉しそう

今夜はいつもより ロマンチックに
ブルーの瞳に 粉雪のハイライト
ぎゅっと抱き寄せて 恋のレイヤー重ねたら
動き出す

Miracle painting
キセキのロマンス
魔法の一筆に 愛をこめて
髪の先まで全て あなただけのものよ
今宵はあなたと 幾つの夢を数えたかな
溢れる思いは
数え切れない 伝え切れない
言い尽くせない まだまだ足りない
だから まだ終わらないで

Miracle painting
キセキのshow time
魔法の一筆に もう夢中よ
もっともっと頂戴 私だけの色を

終わらないで miracle painting
魅惑のテクニック
仕上げはまだ ちょっと待っていてね
あなたに伝えるから 心からの
I love you!

（しゃーばーだばっぱっぱっぱらっぱ）
（しゃーばーだばっぱっぱらっらっぱ）
しゃーばーとぅりらーとぅりらーとぅらら
しゃばらるっぴるららぱるわ